version: '3.4'

services:

  metrics-cli:
    image: "nsidc/noaadata-web-server-metrics:${APP_VERSION}"
    restart: "unless-stopped"
    volumes:
      - "/share/logs/noaa-web/:/share/logs/noaa-web:rw"
    network_mode: "host"
    logging:
      options:
        max-size: "10m"
        max-file: "10"
