version: '3.4'

services:

  data-server:
    image: "nsidc/noaa-web-server-metrics:${SERVER_VERSION:-latest}"
    restart: "unless-stopped"
    volumes:
      - "/share/logs/noaa-web/:/share/logs/noaa-web:ro"
    logging:
      options:
        max-size: "10m"
        max-file: "10"
