name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    tags:
      - "latest"
      - "v*.*.*"
  pull_request:
    branches: [ "main" ]
    
    
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
    - uses: actions/checkout@v3
    
    - name: docker login
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        username: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASS}}

    - name: Extract metadata for the Docker image
      id: meta
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with: 
        images: nsidc/noaadata-web-server-metrics
      
    - name: Build and push the Docker image
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        context: .
        push: true
        tags: ${{ steps.meta.output.tags }}
        labels: ${{ steps.meta.output.labels }}
