name: "Lint"

on: 
  push:
    branches: ["main"]
    tags: ["v[0-9]+.[0-9]+.[0-9].*"]
  pull_request:

jobs:
  lint:
    runs-on: "ubuntu-latest"

    steps:
      - uses: "actions/checkout@v3"

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install Python dependencies
        run: pip install black flake8

      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          black: true
          flake8: true 
